export const VOUCHERS_FIXOS = [
  'ALELO',
  'TICKET',
  'VR',
  'SODEXO',
  'PLUXE',
  'COMPROCARD',
  'LE CARD',
  'UP BRASIL',
  'ECX CARD',
  'FN CARD',
  'BEN VISA',
  'CREDSHOP',
  'RC CARD',
  'GOOD CARD',
  'BIG CARD',
  'BK CARD',
  'GREEN CARD',
  'BRASILCARD',
  'BOLT CARD',
  'CABAL',
  'VEROCARD',
  'FACECARD',
  'VALE CARD',
  'NAIP',
  'NUTRICASH',
  'LIBERCARD',
  'SENFF',
  'ES CARD',
  'ROM CARD'
]

export const ALIASES_TABELA_POR_VOUCHER = {
  TICKET: ['TICKET SERVICOS SA', 'TICKET SERVICOS'],
  VR: ['VR BENEFICIOS', 'VR BENEF', 'BANCO VR', 'VR BENEFCIOS SERV', 'VR BENEFICIOS SERV', 'VR BENEFCIOS SERV'],
  PLUXE: ['PLUXEE', 'PLUXEE BENEFICIOS BR', 'PLUXE BENEFICIOS BR'],
  PLUXEE: ['PLUXE', 'PLUXEE BENEFICIOS BR', 'PLUXE BENEFICIOS BR'],
  ALELO: ['ALELO INSTITUICAO DE PAGAMENTO', 'RECEBIMENTO ALELO'],
  'LE CARD': ['LE CARD ADMINISTRADORA', 'LECARD', 'LE CARD', 'LE CARD ADM'],
  'UP BRASIL': ['UP BRASIL ADMINISTRACAO'],
  'VALE CARD': ['VALECARD', 'AGL ADQUIRENCIA', 'AGL ADQUIRENCIA LTDA'],
  VALECARD: ['VALE CARD', 'AGL ADQUIRENCIA', 'AGL ADQUIRENCIA LTDA'],
  'GREEN CARD': ['GREENCARD', 'GREEN CARD'],
  CABAL: ['CABAL PRE', 'CREDENCIADOR CABAL PRE', 'CABAL BRASIL', 'CREDENCIADOR CABAL BRASIL', 'SICOOB CARTAO CREDITO', 'SICOB CARTAO CREDITO'],
  VEROCARD: ['VEROCHEQUE'],
  'GOOD CARD': ['GOODCARD', 'GOOD CARD'],
  CREDSHOP: ['CREDISHOP', 'CREDI SHOP', 'CRED SHOP'],
  CREDISHOP: ['CREDSHOP', 'CREDI SHOP', 'CRED SHOP'],
  'CREDI SHOP': ['CREDSHOP', 'CREDISHOP', 'CRED SHOP'],
  NUTRICASH: ['NUTRI CASH', 'NUTRIACH', 'NUTRIACASH', 'NUTRICASH SERVICOS LTDA', 'NUTRIACH SERVICOS LTDA', 'NUTRIACASH SERVICOS LTDA'],
  LIBERCARD: ['LIBER CARD', 'LIBERCAD', 'MANDACARU ADMINISTRADORA', 'MANDACARU'],
  'ES CARD': ['ES CARD', 'ES CARD BEN', 'ES_CARD', 'ESCARD', 'ESCARD BEN'],
  'BIG CARD': ['BIGCARD', 'BIGCARD ADMINISTRADORA DE CONVEN'],
  'ROM CARD': ['ROM CARD ADM', 'ROMCARD'],
  'ROM CARD ADM': ['ROM CARD', 'ROMCARD'],
  ROMCARD: ['ROM CARD', 'ROM CARD ADM']
}

export const getOperadorasParaTabela = (voucherNome) => {
  const key = String(voucherNome || '').toUpperCase().trim()
  const aliases = ALIASES_TABELA_POR_VOUCHER[key] || []
  return [voucherNome, ...aliases].filter(Boolean)
}
