export const VOUCHERS_FIXOS = [
  'ALELO',
  'TICKET',
  'VR',
  'SODEXO',
  'PLUXE',
  'COMPROCARD',
  'LE CARD',
  'UP BRASIL',
  'ECX CARD',
  'FN CARD',
  'BEN VISA',
  'CREDSHOP',
  'RC CARD',
  'GOOD CARD',
  'BIG CARD',
  'BK CARD',
  'GREEN CARD',
  'BRASILCARD',
  'BOLT CARD',
  'CABAL',
  'VEROCARD',
  'FACECARD',
  'VALE CARD',
  'NAIP',
  'NUTRICASH',
  'LIBERCARD',
  'SENFF'
]

export const ALIASES_TABELA_POR_VOUCHER = {
  TICKET: ['TICKET SERVICOS SA', 'TICKET SERVICOS'],
  VR: ['VR BENEFICIOS', 'VR BENEF', 'BANCO VR', 'VR BENEFCIOS SERV', 'VR BENEFICIOS SERV', 'VR BENEFCIOS SERV'],
  PLUXE: ['PLUXEE', 'PLUXEE BENEFICIOS BR', 'PLUXE BENEFICIOS BR'],
  ALELO: ['ALELO INSTITUICAO DE PAGAMENTO', 'RECEBIMENTO ALELO'],
  'LE CARD': ['LE CARD ADMINISTRADORA', 'LECARD', 'LE CARD', 'LE CARD ADM'],
  'UP BRASIL': ['UP BRASIL ADMINISTRACAO'],
  'VALE CARD': ['VALECARD'],
  'GREEN CARD': ['GREENCARD', 'GREEN CARD'],
  CABAL: ['CABAL PRE', 'CREDENCIADOR CABAL PRE', 'CABAL BRASIL', 'CREDENCIADOR CABAL BRASIL'],
  VEROCARD: ['VEROCHEQUE'],
  'GOOD CARD': ['GOODCARD', 'GOOD CARD'],
  NUTRICASH: ['NUTRI CASH'],
  LIBERCARD: ['LIBER CARD', 'LIBERCAD', 'MANCACARU', 'MANACARU']
}

export const getOperadorasParaTabela = (voucherNome) => {
  const key = String(voucherNome || '').toUpperCase().trim()
  const aliases = ALIASES_TABELA_POR_VOUCHER[key] || []
  return [voucherNome, ...aliases].filter(Boolean)
}
